### PR TITLE
Shutdown Files

### PR DESCRIPTION
**Pull request by NexusWannaBe**
Added some payloads that will shut down PC

### CODE REVIEW

**Comment by aleff-github** [comment]
@NexusWannaBe, I would like to thank you for deciding to support the project by sharing two payloads. Regarding the payloads, I thought of making some changes to spark a discussion and see if they might improve your work (and keep them) or not (and remove them).

Before reading, I invite you to create a README for your payloads. It could be really nice to have a presentation of the payload, even if it's small and brief.

The first change I made was adding a comment in the script referring to you so that everyone knows that you are the one who created the script, not me.

I added the /f parameter, which forces the closure of all open applications without asking for confirmation. (Warning: You might lose unsaved data.)

I replaced a series of DELAYs and the ALT F4 combo with the concatenation of the exit command to reduce delay times.

I removed a delay between typing the command and executing it since the execution (i.e., sending the ENTER command) only happens after the command has been fully typed.

I renamed the files containing the payload to payload.txt to align them with the style of the others.

I renamed the folder of the file Shutdown_1m to Shutdown_After_1_Minute-By_NexusWannaBe to make the payload name clearer (someone might ask what the letter "m" stands for in the name). Additionally, I added your name at the end so users know that you are the creator, and if they want to give credit, they can give it to you instead of me, who simply revised what you designed and created.

I added the payload to the list of payloads by modifying the two README files.

**Comment by NexusWannaBe** [comment]
Thanks, the payloads are much more faster now and accurate. I also added README files to the forked version of the payloads list

**Review by NexusWannaBe — COMMENTED** [review]
Looks good( idk why i commented twice was tryna make a review but oh well)

**Comment by aleff-github** [comment]
> I also added README files to the forked version of the payloads list

@NexusWannaBe Great, I suggest you upload the READMEs inside this pull request otherwise they would not be uploaded.

To do this you simply move inside the pull 16, if you use gh you can simply enter “gh pr checkout 16” in your terminal

**Comment by NexusWannaBe** [comment]
[README (1).MD](https://github.com/user-attachments/files/17265475/README.1.MD)
[README.MD](https://github.com/user-attachments/files/17265476/README.MD)
here ya go

**Comment by aleff-github** [comment]
> [README (1).MD](https://github.com/user-attachments/files/17265475/README.1.MD) [README.MD](https://github.com/user-attachments/files/17265476/README.MD) here ya go

I created for you two README files that explain well the type of script created, have a look at them ;)

I accept the pull request and put it in the main branch

**Comment by aleff-github** [comment]
Merged just now, you can now find your payloads in these links:
- [Shutdown_After_1_Minute-By_NexusWannaBe](https://github.com/aleff-github/my-flipper-shits/tree/main/Windows/Execution/Shutdown_After_1_Minute-By_NexusWannaBe)
- [Immediate_Shutdown-By_NexusWannaBe](https://github.com/aleff-github/my-flipper-shits/tree/main/Windows/Execution/Immediate_Shutdown-By_NexusWannaBe)

Thank you for voluntarily contributing to the project ^_^

**Comment by aleff-github** [comment]
Consider to see this new update into the repo home page -> https://github.com/aleff-github/my-flipper-shits?tab=readme-ov-file#top-payload-contributors

**Pull request merged**
